### ISSUE TITLE
Create Subscription Model

### ISSUE THREAD

**Issue by beck** [yola/yolapy#18]
ATM, achieved in the consumer via:

```
Yola().list_subscriptions(user_id=site.yola_user_id)
```

Would rather do this via the User model.

Need two things:
1. ability to fetch user
2. fetch subscriptions related to user

Thinking something like:

```
user = User.get(id='abcdef1234567890abcdef1234567890')
subscriptions = user.list_subscriptions()
```

**Comment by blaix** [comment]
When this is done, we will need to update bottmline: https://github.com/yola/bottomline/pull/29#discussion_r42674264

**Comment by blaix** [comment]
> Thinking something like:

``` python
user = User.get(id='abcdef1234567890abcdef1234567890')
subscriptions = user.list_subscriptions()
```

To avoid `User` turning into a god model, what about:

``` python
subscriptions = Subscription.list(user_id='abcdef1234567890abcdef1234567890')
```

which returns a list of `Subscription` instances?

**Comment by beck** [comment]
I like it but am asking myself, what is the advantage of:

```
subscriptions = Subscription.list(user_id='abcdef1234567890abcdef1234567890')
```

over

```
subscriptions =Yola().list_subscriptions(user_id=site.yola_user_id)
```

?

**Comment by stefanor** [comment]
> To avoid User turning into a god model

Is that actually something we want to avoid. Almost everything is tied to the user, one way or another.

As a consumer of the library, I'd probably like to have a `list_subscriptions()` method on the user. Do we want mixins like we have in yousers, to keep this vaguely separated?

**Comment by snitch** [comment]
@beck: This issue is now a priority.

**Comment by blaix** [comment]
Advantage over `Yola.list_subscriptions`: we will want a `Subscription` model. Our service classes return json dicts, not models.

For our models that come from a service, I think the following pattern is appropriate:

``` python
Subscription(**kwargs) # init with raw data (to be sent to the service with a `save()` call for example)
Subscription.get(id=ID) # init with data from the service
Subscription.list(user_id=ID) # init a list of models with data from the service
```

If we do find ourselves wanting `user.list_subscriptions`, we could add that, but I'd want it to use `Subscription.list` internally. In other words, start with the decoupled version, and then couple if the trade-off is worth it. Which is much easier IMO than started with the coupled version and then trying to decouple (which we won't do, because by the time the pain of the coupling causes problems, it's become too entrenched to untangle).

**Comment by beck** [comment]
> Our service classes return json dicts

With use of `QueryList` this is not at all a big deal. Noticed because things break for me when I have a list of models and try to do:

```
subscribed = QueryList(site.subscriptions).filter(type=subscription_type)
```

But I'm digging the pattern:

```
Thing(**kwargs)
Thing.get(id=ID)
Thing.list(foo=Bar)
```

The pull: https://github.com/yola/yolapy/pull/22
